language: java

sudo: false

branches:
  only:
    - travis-integration

addons:
  postgresql: "9.4"

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2

before_install:
# STAGING
  - psql --version
  - psql -U postgres -c 'create database staging;'
  - psql -U postgres -c 'create database rsgb;'
  - psql -U postgres -d rsgb -c 'create extension postgis;'
#  - psql -U postgres --list
  - ls -l ./datamodel/generated_scripts/
# set up RSGB
  - travis_wait psql -U postgres -w -d rsgb -a -f ./datamodel/generated_scripts/datamodel_postgresql.sql
  - ls -l ./datamodel/utility_scripts/
#  - psql -U postgres -d rsgb -a -f ./datamodel/utility_scripts/111a_update_gemeente_geom.sql
#  - psql -U postgres -d rsgb -a -f ./datamodel/utility_scripts/113a_update_wijk_geom.sql

install:
# install all dependencies + artifacts without any testing,
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -Ptravis-ci

before_script:
# dit dient na afloop van de 'install' gedaan te worden omdat de staging DB sql gegenereerd wordt door Hibernate
  - ls -l ./brmo-persistence/target/ddlscripts/
  - psql -U postgres -d staging -a -f ./brmo-persistence/target/ddlscripts/create-brmo-persistence-postgresql.sql
  - ls -l ./brmo-persistence/db/
  - psql -U postgres -d staging -a -f ./brmo-persistence/db/01_create_indexes.sql
  - psql -U postgres -d staging -a -f ./brmo-persistence/db/02_insert_default_user.sql
  - psql -U postgres -d staging -a -f ./brmo-persistence/db/03_update_status_enum_value.sql

# run tests
script:
# run unit tests
  - mvn -e test -B  -Ptravis-ci
# run integration tests
  - mvn -e verify -B -Ptravis-ci

# after_success:

# after_failure:

# after_script:

# notifications:
#   email: false
  #  on_success: [always|never|change] # default: change
  #  on_failure: [always|never|change] # default: always
