dist: trusty
sudo: required
language: java

env:
  global:
    - secure: "gkFOCErQLXQNPRMqkwy55eVYy4Sy/uUHd/LPp7k6PKr3Nx/YmiirtiGAbL5JMrOiQRFDydGlVDAtTUcUqeyKcMkbBNJ7qqrMNXIL0cf5+xDtUeyGa/zm3Ma5R1VrZ6iD/s2e6vju4oW+NycDq5/cUm0roum5psF1eYMqGYv9uZI="
    - secure: "H1aFIto0g/9Uw9BqugqByMtoUOtKtHD2kyCoqVsU9pE3KrlsfdmFf7h04WbuQfefyliX5r7L4eJaHUjLGySp/qka0zEnaKAgQZsS11k21LMjK0xY1KEyROmJ9ogDBoPVrn4NpCBO3RrqH33uEzD0QK97UKp/+ys/2vIlBpQfwy4="

addons:
   postgresql: "9.5"
   # fix voor OpenJDK bufferoverflow, zie:
   #  - https://docs.travis-ci.com/user/hostname
   #  - https://github.com/travis-ci/travis-ci/issues/5227
   #  - https://github.com/travis-ci/travis-ci/issues/5669
   hostname: travis-brmo
   hosts: travis-brmo

jdk:
  - oraclejdk8
  - openjdk8

matrix:
  fast_finish: true

  allow_failures:

cache:
  directories:
  - $HOME/.m2

before_install:
  # installeer een up-2-date Maven versie
  - wget https://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  # installeer/update postgis 2.2 op postgresql 9.5
  - sudo service postgresql stop
  - sudo -E apt-get -qq update &>> ~/apt-get-update.log
  - sudo apt-get -qq install postgis-2.2 gdal-bin graphviz
  - sudo service postgresql stop
  - sudo service postgresql start 9.5
  #- export PGHOST=localhost
  #- export PGPORT=5432
  - export PAGER=cat
  - psql --version
  - psql -U postgres -d postgres -c 'SELECT Version();'
  - psql -U postgres -a -c "CREATE ROLE staging LOGIN PASSWORD 'staging' SUPERUSER CREATEDB;"
  - psql -U postgres -a -c "CREATE ROLE rsgb LOGIN PASSWORD 'rsgb' SUPERUSER CREATEDB;"
  - psql -U postgres -a -c "CREATE ROLE rsgbbgt LOGIN PASSWORD 'rsgbbgt' SUPERUSER CREATEDB;"
  - psql -U postgres -c 'create database staging;'
  - psql -U postgres -c 'create database rsgb;'
  - psql -U postgres -d rsgb -c 'create extension postgis;'
  - psql -U postgres -d rsgb -c 'SELECT PostGIS_full_version();'
  - psql -U postgres -c 'create database rsgbbgt;'
  - psql -U postgres -d rsgbbgt -c 'create extension postgis;'
  - psql -U postgres -d rsgbbgt -c 'SELECT PostGIS_full_version();'

install:
  # install all dependencies + artifacts without any testing and create any DB scripts
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -Ppostgresql -pl '!brmo-dist'

before_script:
  # dit dient na afloop van de 'install' gedaan te worden omdat (een deel van) de sql gegenereerd wordt
  # set up staging db
  - ls -l ./brmo-persistence/db/
  - psql -U postgres -d staging -f ./brmo-persistence/db/create-brmo-persistence-postgresql.sql
  - psql -U postgres -d staging -f ./brmo-persistence/db/01_create_indexes.sql
  - psql -U postgres -d staging -f ./brmo-persistence/db/02_insert_default_user.sql
  # set up rsgb tabellen
  - ls -l ./datamodel/generated_scripts/
  - travis_wait psql -U postgres -w -q -d rsgb -f ./datamodel/generated_scripts/datamodel_postgresql.sql
  #- ls -l ./datamodel/utility_scripts/postgresql/
  #- travis_wait psql -U postgres -w -d rsgb -f ./datamodel/utility_scripts/postgresql/111a_update_gemeente_geom.sql
  #- travis_wait psql -U postgres -w -d rsgb -f ./datamodel/utility_scripts/postgresql/113a_update_wijk_geom.sql
  # set up rsgbbgt tabellen
  - psql -U postgres -w -q -d rsgbbgt -f ./bgt-gml-loader/target/generated-resources/ddl/postgresql/create_rsgb_bgt.sql

script:
  # run unit tests
  - mvn -e test -B -Ppostgresql -pl '!brmo-dist'
  # run integratie tests voor veschillende modules
  # run integratie tests voor bgt-gml-loader module
  - mvn -e verify -B -Ppostgresql -Dtest.onlyITs=true -pl 'bgt-gml-loader'
  # run integratie tests voor brmo-loader module
  - mvn -e verify -B -Ppostgresql -Dtest.onlyITs=true -pl 'brmo-loader'
  # run integratie tests voor brmo-service module
  - travis_wait mvn -e verify -B -Ppostgresql -Dtest.onlyITs=true -pl 'brmo-service'
  # test of javadoc compliant is met java-8 strict checks evt ook mvn javadoc:test-javadoc;
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         travis_wait mvn -Ppostgresql javadoc:javadoc;
         travis_wait mvn -Ppostgresql javadoc:test-javadoc;
    fi

# after_script:

after_success:
  # deploy maven site
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
         travis_wait mvn -B -e -Ppostgresql site-deploy --settings .travis/settings.xml;
    fi

# after_failure:
